config/routes.rb
Rails.application.routes.draw do
  # namespace :api do
  #   namespace :v1 do
  #     root to: 'api#index'

  #     # get 'users', to: 'users#show'
  #     resources :users, only: %i[show new create update destroy]

  #     resources :boards, only: %i[index new show create update destroy] do
  #       resources :contexts, only: %i[index new show create update destroy] do
  #         resources :tasks, only: %i[index new show create update destroy]
  #       end
  #     end
  #   end
  # end

  # namespace :app do
    root to: 'welcome#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    get 'register', to: 'users#new'
    post 'users', to: 'users#create'

    resources :password_resets, only: [:new, :create, :edit, :update]

    # resources :tasks, only: %i[index new create edit update destroy] do
    #   post 'completions', to: 'completions#create'
    #   delete 'completions', to: 'completions#destroy'
    # end

    # resources :boards, only: %i[index new show create edit update destroy] do
    #   resources :contexts, only: %i[new create edit update destroy]
    # end

    resources :boards, only: %i[index new show create update destroy] do
      resources :contexts, only: %i[new show create update destroy] do
        resources :tasks, only: %i[new create edit update destroy] do
          post 'completions', to: 'completions#create'
          delete 'completions', to: 'completions#destroy'
        end
      end
    end
  # end
end

app/views/shared/_dark_button.html.erb
  <%= content_tag :label, nil, class: "dark-button-container" do %>
    <%= check_box_tag '', value: '',  checked: true, id: 'toogle-dark', class: "sr-only peer"  %>
    <%= content_tag :div, '', class:"w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300
    rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full
    peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px]
    after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all
    peer-checked:bg-blue-600" %>
    <%= content_tag :span, 'Dark Theme', class:"ms-3 text-sm font-medium text-gray-900" %>
  <% end %>

app/views/shared/_user_content.html.erb
<%= content_tag :div, class: 'user-container' do %>
  <%= render 'shared/user_info' if current_user.present? %>
<% end %>

app/views/shared/_user_info.html.erb
<%= image_tag 'vinicius'  %>
<%= content_tag :a, href: current_user.present? ? boards_path : root_path do -%>
  <%= content_tag :p, t('welcome.user', user: current_user.name) %>
  <%= content_tag :p, "#{current_user.email}" %>
<% end -%>

app/views/shared/new.html.erb
<%= button_for :button_back, I18n.t('buttons.back'), nil %>

<%= content_tag :h3, @boards.model_name,
    class: 'flex intems-center justify-center font-mono text-lg text-gray-200 mt-10 mx-auto'
%>

<%= content_tag :div, class: '' do %>
  <%= content_tag :div, class: '' do %>
    <%= form_with(scope: @boards, url: @boards,
    method: :post, class: 'form' ) do |form| %>
      <%= content_tag :div, class: '' do %>
        <%= form.label :name, title: 'Nome', class:'' %>
        <%= form.text_field :name, class:'w-full h-16 rounded-xl', placeholder: I18n.t('form.placeholder.default') %>
      <% end %>

      <%= content_tag :div, class: '' do %>
        <%= form.label :description, title: 'Descrição', class:'' %>
        <%= form.text_area :description, class:'w-full h-56 rounded-xl', placeholder: I18n.t('form.placeholder.default') %>
      <% end %>

      <%= form.submit 'Criar Tarefa', class: 'btn-submit' %>
    <% end %>
  <% end %>
<% end %>