config/routes.rb
Rails.application.routes.draw do
  # namespace :api do
  #   namespace :v1 do
  #     root to: 'api#index'

  #     # get 'users', to: 'users#show'
  #     resources :users, only: %i[show new create update destroy]

  #     resources :boards, only: %i[index new show create update destroy] do
  #       resources :contexts, only: %i[index new show create update destroy] do
  #         resources :tasks, only: %i[index new show create update destroy]
  #       end
  #     end
  #   end
  # end

  # namespace :app do
    root to: 'welcome#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    get 'register', to: 'users#new'
    post 'users', to: 'users#create'

    resources :password_resets, only: [:new, :create, :edit, :update]

    # resources :tasks, only: %i[index new create edit update destroy] do
    #   post 'completions', to: 'completions#create'
    #   delete 'completions', to: 'completions#destroy'
    # end

    # resources :boards, only: %i[index new show create edit update destroy] do
    #   resources :contexts, only: %i[new create edit update destroy]
    # end

    resources :boards, only: %i[index new show create update destroy] do
      resources :contexts, only: %i[new show create update destroy] do
        resources :tasks, only: %i[new create edit update destroy] do
          post 'completions', to: 'completions#create'
          delete 'completions', to: 'completions#destroy'
        end
      end
    end
  # end
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :board
  has_many :tasks
  has_many :users, through: :board

  validates :name, presence: true
  validates :description, presence: true
  validates :priority, presence: true
  validates :board_id, presence: true
  validates :priority, numericality: { only_integer: true, greater_than: 0 }
  validates_uniqueness_of :name, :priority, scope: :board_id
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :authenticate!

  def new
    @context = Context.new
  end

  def create
    @context = Context.new(context_params.merge(board_id: params[:board_id]))

    if @context.save
      flash[:success] = t('contexts.create.success')
      redirect_to board_path(params[:board_id])
    else
      flash.now[:error] = t('contexts.create.error', errors: @context.errors.full_messages.join(', '))
      render 'new'
    end
  end

  def show
    @context = Context.find_by_id(params[:id])
    @tasks = @context.tasks
  end

  private

  def context_params
    params.require(:context).permit(:name, :description, :priority)
  end
end

app/views/contexts/new.html.erb
<%= button_for :button_back, t('buttons.back'), board_path(params[:board_id]) %>

<%= content_tag :h3, @context.model_name,
    class: 'flex intems-center justify-center font-mono text-lg text-gray-200 mt-10 mx-auto'
%>

<%= content_tag :div, class: '' do %>
  <%= content_tag :div, class: '' do %>
    <%= form_with(scope: @context, url: board_contexts_path(board_id: params[:board_id]),
        method: :post, class: 'form' ) do |form| %>
      <%= content_tag :div, class: '' do %>
        <%= form.label :name, title: Context.human_attribute_name(:name), class:'' %>
        <%= form.text_field :name, class:'w-full h-16 rounded-xl', placeholder: t('form.placeholder.default') %>
      <% end %>

      <%= content_tag :div, class: '' do %>
        <%= form.label :description, title: Context.human_attribute_name(:description), class:'' %>
        <%= form.text_area :description, class:'w-full h-56 rounded-xl', placeholder: t('form.placeholder.default') %>
      <% end %>

      <%= content_tag :div, class: '' do %>
        <%= form.label :priority, title: Context.human_attribute_name(:priority), class:'' %>
        <%= form.number_field :priority, in: 1..100, step: 1 %>
      <% end %>

      <%= form.submit I18n.t('form.submit.default'), class: 'btn-submit' %>
    <% end %>
  <% end %>
<% end %>

app/views/contexts/show.html.erb
<%= button_for :button_back, t('buttons.back'), board_path(@context.board_id) %>

<%= content_tag :h3, t('task.title'),
    class: 'flex intems-center justify-center font-mono text-sm text-gray-200 mx-auto'
%>

<%= content_tag :div, class: 'grid grid-rows-2 grid-cols-2 grid-flow-row gap-2 hover:gap-4 mt-10 px-2' do %>
  <%= button_for :create, nil, new_board_context_task_path(board_id: params[:board_id], context_id: params[:id]), { class: 'text-gray-200' } if signed? %>

  <% unless @tasks.empty? %>
    <% @tasks.each do |task| %>
      <%= content_tag :div, class: 'bg-red-200 card rounded-2xl shadow-lg py-2 px-4' do %>
        <%= content_tag :div, class: 'p-4' do %>
          <%= content_tag :p, task.description, class: "text-gray-600 text-xs text-left #{'line-through' if task.completed? }" %>
        <% end %>

        <%= content_tag :div, class: 'flex flex-row justify-around text-xs' do %>
          <%= button_for :checkbox, nil, board_context_task_completions_path(board_id: task.board.id, context_id: task.context.id, task_id: task.id), { object: task, class: 'text-gray-200' } %>
          <%= button_for :edit, nil, edit_board_context_task_path(context_id: task.context.id, task_id: task.id), { class: 'text-gray-200' } %>
          <%= button_for :delete, nil, board_context_task_path(board_id: task.board.id, context_id: task.context.id, id: task.id), { class: 'text-gray-200' } %>
        <% end %>
      <% end %>

    <% end %>
  <% end %>
<% end %>