config/routes.rb
Rails.application.routes.draw do
  # namespace :api do
  #   namespace :v1 do
  #     root to: 'api#index'

  #     # get 'users', to: 'users#show'
  #     resources :users, only: %i[show new create update destroy]

  #     resources :boards, only: %i[index new show create update destroy] do
  #       resources :contexts, only: %i[index new show create update destroy] do
  #         resources :tasks, only: %i[index new show create update destroy]
  #       end
  #     end
  #   end
  # end

  # namespace :app do
    root to: 'welcome#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    get 'register', to: 'users#new'
    post 'users', to: 'users#create'

    resources :password_resets, only: [:new, :create, :edit, :update]

    # resources :tasks, only: %i[index new create edit update destroy] do
    #   post 'completions', to: 'completions#create'
    #   delete 'completions', to: 'completions#destroy'
    # end

    # resources :boards, only: %i[index new show create edit update destroy] do
    #   resources :contexts, only: %i[new create edit update destroy]
    # end

    resources :boards, only: %i[index new show create update destroy] do
      resources :contexts, only: %i[new show create update destroy] do
        resources :tasks, only: %i[new create edit update destroy] do
          post 'completions', to: 'completions#create'
          delete 'completions', to: 'completions#destroy'
        end
      end
    end
  # end
end

app/models/board.rb
class Board < ApplicationRecord
  include BoardMethods

  belongs_to :user
  has_many :contexts, dependent: :destroy
  has_many :tasks , through: :contexts

  validates :name, :description, :user_id, presence: true

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate!

  def index
    @boards = current_user ? current_user.boards : Board.default_boards
  end

  def new
    @boards = Board.new
  end

  def create
    @boards = Board.new(board_params.merge(user_id: current_user.id))

    if @boards.save
      flash[:success] = t('boards.create.success')
      redirect_to boards_path
    else
      flash.now[:error] = t('boards.create.error', errors: @boards.errors.full_messages.join(', '))
      render 'new'
    end
  end

  def show
    @boards = Board.find_by_id(params[:id])
    @contexts = @boards.contexts
  end

  private

  def board_params
    params.require(:board).permit(:name, :description)
  end
end

app/views/boards/index.html.erb
<%= content_tag :h3, t('board.welcome'),
    class: 'flex intems-center justify-center font-mono text-sm text-gray-200 text-center mx-auto'
%>

<%= content_tag :div, class: 'grid grid-rows-2 grid-cols-2 grid-flow-row gap-2 hover:gap-4 mt-10 px-2' do %>
  <%= button_for :create, nil, new_board_path, { class: 'text-gray-200' } if signed? %>

  <% @boards.each do |board| %>
    <%= link_to board_path(board), class: '' do %>
      <%= content_tag :div, class: 'bg-blue-300 card rounded-2xl shadow-lg' do %>
        <%= content_tag :div, class: 'p-4' do %>
          <%= content_tag :h2, board.name, class: 'font-bold text-lg' %>
          <%= content_tag :p, board.description, class: 'text-gray-700 text-xs' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/boards/new.html.erb
<%= button_for :button_back, t('buttons.back'), nil %>

<%= content_tag :h3, @boards.model_name,
    class: 'flex intems-center justify-center font-mono text-lg text-gray-200 mt-10 mx-auto'
%>

<%= content_tag :div, class: '' do %>
  <%= content_tag :div, class: '' do %>
    <%= form_with(scope: @boards, url: @boards,
        method: :post, class: 'form' ) do |form| %>
      <%= content_tag :div, class: '' do %>
        <%= form.label :name, title: Board.human_attribute_name(:name), class:'' %>
        <%= form.text_field :name, class:'w-full h-16 rounded-xl', placeholder: t('form.placeholder.default') %>
      <% end %>

      <%= content_tag :div, class: '' do %>
        <%= form.label :description, title: Board.human_attribute_name(:description), class:'' %>
        <%= form.text_area :description, class:'w-full h-56 rounded-xl', placeholder: t('form.placeholder.default') %>
      <% end %>

      <%= form.submit t('form.submit.default'), class: 'btn-submit' %>
    <% end %>
  <% end %>
<% end %>

app/views/boards/show.html.erb
<%= button_for :button_back, t('buttons.back'), boards_path %>

<%= content_tag :h3, t('board.list'),
    class: 'flex intems-center justify-center font-mono text-sm text-gray-200 mx-auto'
%>

<%= content_tag :div, class: 'grid grid-rows-2 grid-cols-2 grid-flow-row gap-2 hover:gap-4 mt-10 px-2' do %>
  <%= button_for :create, nil, new_board_context_path(board_id: params[:id]), { class: 'text-gray-200' } if signed? %>

  <% unless @contexts.empty? %>
    <% @contexts.each do |context| %>
      <%= link_to board_context_path(board_id: @boards.id, id: context.id), class: '' do %>
        <%= content_tag :div, class: 'bg-orange-200 card rounded-2xl shadow-lg' do %>
          <%= content_tag :div, class: 'p-4' do %>
            <%= content_tag :h3, context.name, class: 'font-bold text-lg' %>
            <%= content_tag :p, context.description, class: 'text-gray-700 text-xs' %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>